apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-deployment
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: cnt1
          image: rg.fr-par.scw.cloud/demoregistry/statusapp:v1
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "while true; do sleep 30; done;" ]
          command: [ "/bin/bash", "/opt/status-page/start2.sh" ]
          args: ["/opt/status-page/start2.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /opt/status-page/statuspage/statuspage/configuration.py
            subPath: config1
      volumes:
        - name: config-volume
          configMap:
            name: cm-configuration
